import * as React from 'react';
export interface Touch {
    startX: number;
    startY: number;
    endX: number;
    endY: number;
    swipeDirection: number;
}
export interface CarouselProps {
    label?: string;
    useDots?: boolean;
    dotStyle?: React.CSSProperties;
    activeDotStyle?: React.CSSProperties;
    duration?: number;
    autoSlideInterval?: number;
    style?: React.CSSProperties;
    useControl?: boolean;
}
export interface CarouselState {
    animate: boolean;
    canUseDOM: boolean;
    currentIndex: number;
    slideCount: number;
    slideWidth: any;
    slideHeight: any;
    swipePosition: number;
    showIndex: number;
}
export default class Carousel extends React.Component<CarouselProps, CarouselState> {
    id: string;
    container: Element;
    swiping: boolean;
    moving: boolean;
    direction: number;
    touch: Touch;
    timer: any;
    static readonly defaultProps: CarouselProps;
    constructor(props: any);
    componentDidMount(): void;
    componentDidUpdate(prevProps: any): void;
    componentWillUnmount(): void;
    render(): JSX.Element;
    renderInitialRect(): JSX.Element;
    renderCarouselChild(): JSX.Element | JSX.Element[];
    renderControls(): JSX.Element;
    renderNextButton(action: any): JSX.Element;
    renderPrevButton(action: any): JSX.Element;
    autoSlide(): void;
    resetAutoSlide(): void;
    addEvents(): void;
    removeEvents(): void;
    onResize: () => void;
    getFrameStyle(): any;
    getSlideStyle(index: any): any;
    canDisplaySlide(index: any): boolean;
    getNextIndex(): number;
    getPrevIndex(): number;
    getIndexDirection(index: any): 0 | 1 | -1;
    getButtonStyle(isActive: any): {
        alignContent?: string;
        alignItems?: string;
        alignSelf?: string;
        animationDelay?: string;
        animationDirection?: string;
        animationDuration?: string;
        animationFillMode?: string;
        animationIterationCount?: string | number;
        animationName?: string;
        animationPlayState?: string;
        animationTimingFunction?: string;
        appearance?: import("csstype").AppearanceProperty;
        backdropFilter?: string;
        backfaceVisibility?: import("csstype").BackfaceVisibilityProperty;
        backgroundAttachment?: string;
        backgroundBlendMode?: string;
        backgroundClip?: string;
        backgroundColor?: string;
        backgroundImage?: string;
        backgroundOrigin?: string;
        backgroundPosition?: string | number;
        backgroundPositionX?: string | number;
        backgroundPositionY?: string | number;
        backgroundRepeat?: string;
        backgroundSize?: string | number;
        blockOverflow?: string;
        blockSize?: string | number;
        borderBlockEndColor?: string;
        borderBlockEndStyle?: string;
        borderBlockEndWidth?: string | number;
        borderBlockStartColor?: string;
        borderBlockStartStyle?: string;
        borderBlockStartWidth?: string | number;
        borderBottomColor?: string;
        borderBottomLeftRadius?: string | number;
        borderBottomRightRadius?: string | number;
        borderBottomStyle?: import("csstype").BorderBottomStyleProperty;
        borderBottomWidth?: string | number;
        borderCollapse?: import("csstype").BorderCollapseProperty;
        borderImageOutset?: string | number;
        borderImageRepeat?: string;
        borderImageSlice?: string | number;
        borderImageSource?: string;
        borderImageWidth?: string | number;
        borderInlineEndColor?: string;
        borderInlineEndStyle?: string;
        borderInlineEndWidth?: string | number;
        borderInlineStartColor?: string;
        borderInlineStartStyle?: string;
        borderInlineStartWidth?: string | number;
        borderLeftColor?: string;
        borderLeftStyle?: import("csstype").BorderBottomStyleProperty;
        borderLeftWidth?: string | number;
        borderRightColor?: string;
        borderRightStyle?: import("csstype").BorderBottomStyleProperty;
        borderRightWidth?: string | number;
        borderSpacing?: string | number;
        borderTopColor?: string;
        borderTopLeftRadius?: string | number;
        borderTopRightRadius?: string | number;
        borderTopStyle?: import("csstype").BorderBottomStyleProperty;
        borderTopWidth?: string | number;
        bottom?: string | number;
        boxAlign?: import("csstype").BoxAlignProperty;
        boxDecorationBreak?: import("csstype").BoxDecorationBreakProperty;
        boxFlexGroup?: import("csstype").GlobalsNumber;
        boxLines?: import("csstype").BoxLinesProperty;
        boxOrdinalGroup?: import("csstype").GlobalsNumber;
        boxShadow?: string;
        boxSizing?: import("csstype").BoxSizingProperty;
        breakAfter?: import("csstype").BreakAfterProperty;
        breakBefore?: import("csstype").BreakAfterProperty;
        breakInside?: import("csstype").BreakInsideProperty;
        captionSide?: import("csstype").CaptionSideProperty;
        caretColor?: string;
        clear?: import("csstype").ClearProperty;
        clipPath?: string;
        color?: string;
        colorAdjust?: import("csstype").ColorAdjustProperty;
        columnCount?: import("csstype").ColumnCountProperty;
        columnFill?: import("csstype").ColumnFillProperty;
        columnGap?: string | number;
        columnRuleColor?: string;
        columnRuleStyle?: string;
        columnRuleWidth?: string | number;
        columnSpan?: import("csstype").ColumnSpanProperty;
        columnWidth?: string | number;
        contain?: string;
        content?: string;
        counterIncrement?: string;
        counterReset?: string;
        cursor: string;
        direction?: import("csstype").DirectionProperty;
        display?: string;
        emptyCells?: import("csstype").EmptyCellsProperty;
        filter?: string;
        flexBasis?: string | number;
        flexDirection?: import("csstype").FlexDirectionProperty;
        flexGrow?: import("csstype").GlobalsNumber;
        flexShrink?: import("csstype").GlobalsNumber;
        flexWrap?: import("csstype").FlexWrapProperty;
        float?: import("csstype").FloatProperty;
        fontFamily?: string;
        fontFeatureSettings?: string;
        fontKerning?: import("csstype").FontKerningProperty;
        fontLanguageOverride?: string;
        fontOpticalSizing?: import("csstype").FontOpticalSizingProperty;
        fontSize?: string | number;
        fontSizeAdjust?: import("csstype").FontSizeAdjustProperty;
        fontStretch?: string;
        fontStyle?: string;
        fontSynthesis?: string;
        fontVariant?: string;
        fontVariantCaps?: import("csstype").FontVariantCapsProperty;
        fontVariantEastAsian?: string;
        fontVariantLigatures?: string;
        fontVariantNumeric?: string;
        fontVariantPosition?: import("csstype").FontVariantPositionProperty;
        fontVariationSettings?: string;
        fontWeight?: import("csstype").FontWeightProperty;
        gridAutoColumns?: string | number;
        gridAutoFlow?: string;
        gridAutoRows?: string | number;
        gridColumnEnd?: string | number;
        gridColumnStart?: string | number;
        gridRowEnd?: string | number;
        gridRowStart?: string | number;
        gridTemplateAreas?: string;
        gridTemplateColumns?: string | number;
        gridTemplateRows?: string | number;
        hangingPunctuation?: string;
        height?: string | number;
        hyphens?: import("csstype").HyphensProperty;
        imageOrientation?: string;
        imageRendering?: import("csstype").ImageRenderingProperty;
        imageResolution?: string;
        initialLetter?: string | number;
        initialLetterAlign?: import("csstype").InitialLetterAlignProperty;
        inlineSize?: string | number;
        isolation?: import("csstype").IsolationProperty;
        justifyContent?: string;
        justifyItems?: string;
        justifySelf?: string;
        left?: string | number;
        letterSpacing?: string | number;
        lineBreak?: import("csstype").LineBreakProperty;
        lineHeight: string | number;
        lineHeightStep?: string | number;
        listStyleImage?: string;
        listStylePosition?: import("csstype").ListStylePositionProperty;
        listStyleType?: string;
        marginBlockEnd?: string | number;
        marginBlockStart?: string | number;
        marginBottom?: string | number;
        marginInlineEnd?: string | number;
        marginInlineStart?: string | number;
        marginLeft?: string | number;
        marginRight?: string | number;
        marginTop?: string | number;
        maskBorderMode?: import("csstype").MaskBorderModeProperty;
        maskBorderOutset?: string | number;
        maskBorderRepeat?: string;
        maskBorderSlice?: string | number;
        maskBorderSource?: string;
        maskBorderWidth?: string | number;
        maskClip?: string;
        maskComposite?: string;
        maskImage?: string;
        maskMode?: string;
        maskOrigin?: string;
        maskPosition?: string | number;
        maskRepeat?: string;
        maskSize?: string | number;
        maskType?: import("csstype").MaskBorderModeProperty;
        maxBlockSize?: string | number;
        maxHeight?: string | number;
        maxInlineSize?: string | number;
        maxLines?: import("csstype").FontSizeAdjustProperty;
        maxWidth?: string | number;
        minBlockSize?: string | number;
        minHeight?: string | number;
        minInlineSize?: string | number;
        minWidth?: string | number;
        mixBlendMode?: import("csstype").MixBlendModeProperty;
        motionDistance?: string | number;
        motionPath?: string;
        motionRotation?: string;
        objectFit?: import("csstype").ObjectFitProperty;
        objectPosition?: string | number;
        offsetAnchor?: string | number;
        offsetBlockEnd?: string | number;
        offsetBlockStart?: string | number;
        offsetDistance?: string | number;
        offsetInlineEnd?: string | number;
        offsetInlineStart?: string | number;
        offsetPath?: string;
        offsetPosition?: string | number;
        offsetRotate?: string;
        offsetRotation?: string;
        opacity?: import("csstype").GlobalsNumber;
        order?: import("csstype").GlobalsNumber;
        orphans?: import("csstype").GlobalsNumber;
        outlineColor?: string;
        outlineOffset?: string | number;
        outlineStyle?: import("csstype").OutlineStyleProperty;
        outlineWidth?: string | number;
        overflow?: string;
        overflowAnchor?: import("csstype").FontOpticalSizingProperty;
        overflowBlock?: string;
        overflowClipBox?: import("csstype").OverflowClipBoxProperty;
        overflowInline?: string;
        overflowWrap?: import("csstype").OverflowWrapProperty;
        overflowX?: import("csstype").OverflowXProperty;
        overflowY?: import("csstype").OverflowXProperty;
        overscrollBehavior?: string;
        overscrollBehaviorX?: import("csstype").OverscrollBehaviorXProperty;
        overscrollBehaviorY?: import("csstype").OverscrollBehaviorXProperty;
        paddingBlockEnd?: string | number;
        paddingBlockStart?: string | number;
        paddingBottom?: string | number;
        paddingInlineEnd?: string | number;
        paddingInlineStart?: string | number;
        paddingLeft?: string | number;
        paddingRight?: string | number;
        paddingTop?: string | number;
        pageBreakAfter?: import("csstype").PageBreakAfterProperty;
        pageBreakBefore?: import("csstype").PageBreakAfterProperty;
        pageBreakInside?: import("csstype").PageBreakInsideProperty;
        paintOrder?: string;
        perspective?: string | number;
        perspectiveOrigin?: string | number;
        placeContent?: string;
        pointerEvents?: import("csstype").PointerEventsProperty;
        position?: import("csstype").PositionProperty;
        quotes?: string;
        resize?: import("csstype").ResizeProperty;
        right?: string | number;
        rotate?: string;
        rowGap?: string | number;
        rubyAlign?: import("csstype").RubyAlignProperty;
        rubyMerge?: import("csstype").RubyMergeProperty;
        rubyPosition?: import("csstype").RubyPositionProperty;
        scale?: string | number;
        scrollBehavior?: import("csstype").ScrollBehaviorProperty;
        scrollSnapType?: import("csstype").ScrollSnapTypeProperty;
        shapeImageThreshold?: import("csstype").GlobalsNumber;
        shapeMargin?: string | number;
        shapeOutside?: string;
        tabSize?: string | number;
        tableLayout?: import("csstype").TableLayoutProperty;
        textAlign?: import("csstype").TextAlignProperty;
        textAlignLast?: import("csstype").TextAlignLastProperty;
        textCombineUpright?: string;
        textDecorationColor?: string;
        textDecorationLine?: string;
        textDecorationSkip?: string;
        textDecorationSkipInk?: import("csstype").FontOpticalSizingProperty;
        textDecorationStyle?: import("csstype").TextDecorationStyleProperty;
        textEmphasisColor?: string;
        textEmphasisPosition?: string;
        textEmphasisStyle?: string;
        textIndent?: string | number;
        textJustify?: import("csstype").TextJustifyProperty;
        textOrientation?: import("csstype").TextOrientationProperty;
        textOverflow?: string;
        textRendering?: import("csstype").TextRenderingProperty;
        textShadow?: string;
        textSizeAdjust?: string;
        textTransform?: import("csstype").TextTransformProperty;
        textUnderlinePosition?: string;
        top?: string | number;
        touchAction?: string;
        transform?: string;
        transformBox?: import("csstype").TransformBoxProperty;
        transformOrigin?: string | number;
        transformStyle?: import("csstype").TransformStyleProperty;
        transitionDelay?: string;
        transitionDuration?: string;
        transitionProperty?: string;
        transitionTimingFunction?: string;
        translate?: string | number;
        unicodeBidi?: import("csstype").UnicodeBidiProperty;
        userSelect?: import("csstype").UserSelectProperty;
        verticalAlign?: string | number;
        visibility?: import("csstype").VisibilityProperty;
        whiteSpace?: import("csstype").WhiteSpaceProperty;
        widows?: import("csstype").GlobalsNumber;
        width?: string | number;
        willChange?: string;
        wordBreak?: import("csstype").WordBreakProperty;
        wordSpacing?: string | number;
        wordWrap?: import("csstype").OverflowWrapProperty;
        writingMode?: import("csstype").WritingModeProperty;
        zIndex?: import("csstype").ColumnCountProperty;
        zoom?: string | number;
        all?: import("csstype").Globals;
        animation?: string | number;
        'background': string | number;
        border: string | number;
        borderBlockEnd?: string | number;
        borderBlockStart?: string | number;
        borderBottom?: string | number;
        borderColor?: string;
        borderImage?: string | number;
        borderInlineEnd?: string | number;
        borderInlineStart?: string | number;
        borderLeft?: string | number;
        borderRadius: string | number;
        borderRight?: string | number;
        borderStyle?: string;
        borderTop?: string | number;
        borderWidth?: string | number;
        columnRule?: string | number;
        columns?: string | number;
        flex?: string | number;
        flexFlow?: string;
        font?: string;
        gap?: string | number;
        grid?: string;
        gridArea?: string | number;
        gridColumn?: string | number;
        gridRow?: string | number;
        gridTemplate?: string;
        lineClamp?: import("csstype").FontSizeAdjustProperty;
        listStyle?: string;
        margin: string | number;
        mask?: string | number;
        maskBorder?: string | number;
        motion?: string | number;
        offset?: string | number;
        outline?: string | number;
        padding: string | number;
        textDecoration?: string;
        textEmphasis?: string;
        transition?: string;
        MozAnimationDelay?: string;
        MozAnimationDirection?: string;
        MozAnimationDuration?: string;
        MozAnimationFillMode?: string;
        MozAnimationIterationCount?: string | number;
        MozAnimationName?: string;
        MozAnimationPlayState?: string;
        MozAnimationTimingFunction?: string;
        MozAppearance?: import("csstype").MozAppearanceProperty;
        MozBackfaceVisibility?: import("csstype").BackfaceVisibilityProperty;
        MozBinding?: string;
        MozBorderBottomColors?: string;
        MozBorderEndColor?: string;
        MozBorderEndStyle?: string;
        MozBorderEndWidth?: string | number;
        MozBorderLeftColors?: string;
        MozBorderRightColors?: string;
        MozBorderStartColor?: string;
        MozBorderStartStyle?: string;
        MozBorderTopColors?: string;
        MozBoxSizing?: import("csstype").BoxSizingProperty;
        MozColumnCount?: import("csstype").ColumnCountProperty;
        MozColumnFill?: import("csstype").ColumnFillProperty;
        MozColumnGap?: string | number;
        MozColumnRuleColor?: string;
        MozColumnRuleStyle?: string;
        MozColumnRuleWidth?: string | number;
        MozColumnWidth?: string | number;
        MozContextProperties?: string;
        MozFloatEdge?: import("csstype").MozFloatEdgeProperty;
        MozFontFeatureSettings?: string;
        MozFontLanguageOverride?: string;
        MozForceBrokenImageIcon?: import("csstype").GlobalsNumber;
        MozHyphens?: import("csstype").HyphensProperty;
        MozImageRegion?: string;
        MozMarginEnd?: string | number;
        MozMarginStart?: string | number;
        MozOrient?: import("csstype").MozOrientProperty;
        MozOutlineRadiusBottomleft?: string | number;
        MozOutlineRadiusBottomright?: string | number;
        MozOutlineRadiusTopleft?: string | number;
        MozOutlineRadiusTopright?: string | number;
        MozPaddingEnd?: string | number;
        MozPaddingStart?: string | number;
        MozPerspective?: string | number;
        MozPerspectiveOrigin?: string | number;
        MozStackSizing?: import("csstype").MozStackSizingProperty;
        MozTabSize?: string | number;
        MozTextBlink?: import("csstype").MozTextBlinkProperty;
        MozTextSizeAdjust?: string;
        MozTransformOrigin?: string | number;
        MozTransformStyle?: import("csstype").TransformStyleProperty;
        MozTransitionDelay?: string;
        MozTransitionDuration?: string;
        MozTransitionProperty?: string;
        MozTransitionTimingFunction?: string;
        MozUserFocus?: import("csstype").MozUserFocusProperty;
        MozUserInput?: import("csstype").MozUserInputProperty;
        MozUserModify?: import("csstype").MozUserModifyProperty;
        MozUserSelect?: import("csstype").UserSelectProperty;
        MozWindowDragging?: import("csstype").MozWindowDraggingProperty;
        MozWindowShadow?: import("csstype").MozWindowShadowProperty;
        msAccelerator?: import("csstype").MsAcceleratorProperty;
        msAlignSelf?: string;
        msBlockProgression?: import("csstype").MsBlockProgressionProperty;
        msContentZoomChaining?: import("csstype").MsContentZoomChainingProperty;
        msContentZoomLimitMax?: string;
        msContentZoomLimitMin?: string;
        msContentZoomSnapPoints?: string;
        msContentZoomSnapType?: import("csstype").ScrollSnapTypeProperty;
        msContentZooming?: import("csstype").MsContentZoomingProperty;
        msFilter?: string;
        msFlexDirection?: import("csstype").FlexDirectionProperty;
        msFlexPositive?: import("csstype").GlobalsNumber;
        msFlowFrom?: string;
        msFlowInto?: string;
        msGridColumns?: string | number;
        msGridRows?: string | number;
        msHighContrastAdjust?: import("csstype").FontOpticalSizingProperty;
        msHyphenateLimitChars?: string | number;
        msHyphenateLimitLines?: import("csstype").MsHyphenateLimitLinesProperty;
        msHyphenateLimitZone?: string | number;
        msHyphens?: import("csstype").HyphensProperty;
        msImeAlign?: import("csstype").MsImeAlignProperty;
        msLineBreak?: import("csstype").LineBreakProperty;
        msOrder?: import("csstype").GlobalsNumber;
        msOverflowStyle?: import("csstype").MsOverflowStyleProperty;
        msOverflowX?: import("csstype").OverflowXProperty;
        msOverflowY?: import("csstype").OverflowXProperty;
        msScrollChaining?: import("csstype").MsContentZoomChainingProperty;
        msScrollLimitXMax?: string | number;
        msScrollLimitXMin?: string | number;
        msScrollLimitYMax?: string | number;
        msScrollLimitYMin?: string | number;
        msScrollRails?: import("csstype").MsScrollRailsProperty;
        msScrollSnapPointsX?: string;
        msScrollSnapPointsY?: string;
        msScrollSnapType?: import("csstype").ScrollSnapTypeProperty;
        msScrollTranslation?: import("csstype").MsScrollTranslationProperty;
        msTextAutospace?: import("csstype").MsTextAutospaceProperty;
        msTextCombineHorizontal?: string;
        msTextOverflow?: string;
        msTextSizeAdjust?: string;
        msTouchAction?: string;
        msTouchSelect?: import("csstype").MsTouchSelectProperty;
        msTransform?: string;
        msTransformOrigin?: string | number;
        msUserSelect?: import("csstype").MsUserSelectProperty;
        msWordBreak?: import("csstype").WordBreakProperty;
        msWrapFlow?: import("csstype").MsWrapFlowProperty;
        msWrapMargin?: string | number;
        msWrapThrough?: import("csstype").MsWrapThroughProperty;
        msWritingMode?: import("csstype").WritingModeProperty;
        OBackgroundSize?: string | number;
        OObjectFit?: import("csstype").ObjectFitProperty;
        OObjectPosition?: string | number;
        OTabSize?: string | number;
        OTextOverflow?: string;
        OTransformOrigin?: string | number;
        WebkitAlignContent?: string;
        WebkitAlignItems?: string;
        WebkitAlignSelf?: string;
        WebkitAnimationDelay?: string;
        WebkitAnimationDirection?: string;
        WebkitAnimationDuration?: string;
        WebkitAnimationFillMode?: string;
        WebkitAnimationIterationCount?: string | number;
        WebkitAnimationName?: string;
        WebkitAnimationPlayState?: string;
        WebkitAnimationTimingFunction?: string;
        WebkitAppearance?: import("csstype").WebkitAppearanceProperty;
        WebkitBackdropFilter?: string;
        WebkitBackfaceVisibility?: import("csstype").BackfaceVisibilityProperty;
        WebkitBackgroundSize?: string | number;
        WebkitBorderBeforeColor?: string;
        WebkitBorderBeforeStyle?: string;
        WebkitBorderBeforeWidth?: string | number;
        WebkitBorderBottomLeftRadius?: string | number;
        WebkitBorderBottomRightRadius?: string | number;
        WebkitBorderImageSlice?: string | number;
        WebkitBorderTopLeftRadius?: string | number;
        WebkitBorderTopRightRadius?: string | number;
        WebkitBoxDecorationBreak?: import("csstype").BoxDecorationBreakProperty;
        WebkitBoxReflect?: string | number;
        WebkitBoxShadow?: string;
        WebkitBoxSizing?: import("csstype").BoxSizingProperty;
        WebkitClipPath?: string;
        WebkitColorAdjust?: import("csstype").ColorAdjustProperty;
        WebkitColumnCount?: import("csstype").ColumnCountProperty;
        WebkitColumnGap?: string | number;
        WebkitColumnRuleColor?: string;
        WebkitColumnRuleStyle?: string;
        WebkitColumnRuleWidth?: string | number;
        WebkitColumnSpan?: import("csstype").ColumnSpanProperty;
        WebkitColumnWidth?: string | number;
        WebkitFilter?: string;
        WebkitFlexBasis?: string | number;
        WebkitFlexDirection?: import("csstype").FlexDirectionProperty;
        WebkitFlexGrow?: import("csstype").GlobalsNumber;
        WebkitFlexShrink?: import("csstype").GlobalsNumber;
        WebkitFlexWrap?: import("csstype").FlexWrapProperty;
        WebkitFontFeatureSettings?: string;
        WebkitFontKerning?: import("csstype").FontKerningProperty;
        WebkitFontVariantLigatures?: string;
        WebkitHyphens?: import("csstype").HyphensProperty;
        WebkitJustifyContent?: string;
        WebkitLineBreak?: import("csstype").LineBreakProperty;
        WebkitMarginEnd?: string | number;
        WebkitMarginStart?: string | number;
        WebkitMaskAttachment?: string;
        WebkitMaskClip?: string;
        WebkitMaskComposite?: string;
        WebkitMaskImage?: string;
        WebkitMaskOrigin?: string;
        WebkitMaskPosition?: string | number;
        WebkitMaskPositionX?: string | number;
        WebkitMaskPositionY?: string | number;
        WebkitMaskRepeat?: string;
        WebkitMaskRepeatX?: import("csstype").WebkitMaskRepeatXProperty;
        WebkitMaskRepeatY?: import("csstype").WebkitMaskRepeatXProperty;
        WebkitMaskSize?: string | number;
        WebkitMaxInlineSize?: string | number;
        WebkitOrder?: import("csstype").GlobalsNumber;
        WebkitOverflowScrolling?: import("csstype").WebkitOverflowScrollingProperty;
        WebkitPaddingEnd?: string | number;
        WebkitPaddingStart?: string | number;
        WebkitPerspective?: string | number;
        WebkitPerspectiveOrigin?: string | number;
        WebkitScrollSnapType?: import("csstype").ScrollSnapTypeProperty;
        WebkitShapeMargin?: string | number;
        WebkitTapHighlightColor?: string;
        WebkitTextCombine?: string;
        WebkitTextDecorationColor?: string;
        WebkitTextDecorationLine?: string;
        WebkitTextDecorationSkip?: string;
        WebkitTextDecorationStyle?: import("csstype").TextDecorationStyleProperty;
        WebkitTextEmphasisColor?: string;
        WebkitTextEmphasisPosition?: string;
        WebkitTextEmphasisStyle?: string;
        WebkitTextFillColor?: string;
        WebkitTextOrientation?: import("csstype").TextOrientationProperty;
        WebkitTextSizeAdjust?: string;
        WebkitTextStrokeColor?: string;
        WebkitTextStrokeWidth?: string | number;
        WebkitTouchCallout?: import("csstype").WebkitTouchCalloutProperty;
        WebkitTransform?: string;
        WebkitTransformOrigin?: string | number;
        WebkitTransformStyle?: import("csstype").TransformStyleProperty;
        WebkitTransitionDelay?: string;
        WebkitTransitionDuration?: string;
        WebkitTransitionProperty?: string;
        WebkitTransitionTimingFunction?: string;
        WebkitUserModify?: import("csstype").WebkitUserModifyProperty;
        WebkitUserSelect?: import("csstype").UserSelectProperty;
        WebkitWritingMode?: import("csstype").WritingModeProperty;
        MozAnimation?: string | number;
        MozBorderImage?: string | number;
        MozColumnRule?: string | number;
        MozColumns?: string | number;
        MozOutlineRadius?: string | number;
        MozTransition?: string;
        msContentZoomLimit?: string;
        msContentZoomSnap?: string;
        msFlex?: string | number;
        msScrollLimit?: string;
        msScrollSnapX?: string;
        msScrollSnapY?: string;
        OBorderImage?: string | number;
        WebkitAnimation?: string | number;
        WebkitBorderBefore?: string | number;
        WebkitBorderImage?: string | number;
        WebkitBorderRadius?: string | number;
        WebkitColumnRule?: string | number;
        WebkitColumns?: string | number;
        WebkitFlex?: string | number;
        WebkitFlexFlow?: string;
        WebkitLineClamp?: import("csstype").FontSizeAdjustProperty;
        WebkitMask?: string | number;
        WebkitTextEmphasis?: string;
        WebkitTextStroke?: string | number;
        WebkitTransition?: string;
        azimuth?: string;
        boxDirection?: import("csstype").BoxDirectionProperty;
        boxFlex?: import("csstype").GlobalsNumber;
        boxOrient?: import("csstype").BoxOrientProperty;
        boxPack?: import("csstype").BoxPackProperty;
        clip?: string;
        fontVariantAlternates?: string;
        gridColumnGap?: string | number;
        gridGap?: string | number;
        gridRowGap?: string | number;
        imeMode?: import("csstype").ImeModeProperty;
        scrollSnapCoordinate?: string | number;
        scrollSnapDestination?: string | number;
        scrollSnapPointsX?: string;
        scrollSnapPointsY?: string;
        scrollSnapTypeX?: import("csstype").ScrollSnapTypeProperty;
        scrollSnapTypeY?: import("csstype").ScrollSnapTypeProperty;
        textCombineHorizontal?: string;
        KhtmlBoxDirection?: import("csstype").BoxDirectionProperty;
        KhtmlBoxFlex?: import("csstype").GlobalsNumber;
        KhtmlBoxOrient?: import("csstype").BoxOrientProperty;
        KhtmlBoxPack?: import("csstype").BoxPackProperty;
        MozBackgroundInlinePolicy?: import("csstype").BoxDecorationBreakProperty;
        MozBackgroundSize?: string | number;
        MozBorderRadius?: string | number;
        MozBorderRadiusBottomleft?: string | number;
        MozBorderRadiusBottomright?: string | number;
        MozBorderRadiusTopleft?: string | number;
        MozBorderRadiusTopright?: string | number;
        MozBoxDirection?: import("csstype").BoxDirectionProperty;
        MozBoxFlex?: import("csstype").GlobalsNumber;
        MozBoxOrient?: import("csstype").BoxOrientProperty;
        MozBoxPack?: import("csstype").BoxPackProperty;
        MozBoxShadow?: string;
        MozOpacity?: import("csstype").GlobalsNumber;
        MozOutline?: string | number;
        MozOutlineColor?: string;
        MozOutlineStyle?: import("csstype").OutlineStyleProperty;
        MozOutlineWidth?: string | number;
        MozResize?: import("csstype").ResizeProperty;
        MozTextAlignLast?: import("csstype").TextAlignLastProperty;
        MozTextDecorationColor?: string;
        MozTextDecorationLine?: string;
        MozTextDecorationStyle?: import("csstype").TextDecorationStyleProperty;
        msImeMode?: import("csstype").ImeModeProperty;
        msScrollbar3dlightColor?: string;
        msScrollbarArrowColor?: string;
        msScrollbarBaseColor?: string;
        msScrollbarDarkshadowColor?: string;
        msScrollbarFaceColor?: string;
        msScrollbarHighlightColor?: string;
        msScrollbarShadowColor?: string;
        msScrollbarTrackColor?: string;
        OAnimation?: string | number;
        OAnimationDelay?: string;
        OAnimationDirection?: string;
        OAnimationDuration?: string;
        OAnimationFillMode?: string;
        OAnimationIterationCount?: string | number;
        OAnimationName?: string;
        OAnimationPlayState?: string;
        OAnimationTimingFunction?: string;
        OTransform?: string;
        OTransition?: string;
        OTransitionDelay?: string;
        OTransitionDuration?: string;
        OTransitionProperty?: string;
        OTransitionTimingFunction?: string;
        WebkitBoxDirection?: import("csstype").BoxDirectionProperty;
        WebkitBoxFlex?: import("csstype").GlobalsNumber;
        WebkitBoxOrient?: import("csstype").BoxOrientProperty;
        WebkitBoxPack?: import("csstype").BoxPackProperty;
        WebkitScrollSnapPointsX?: string;
        WebkitScrollSnapPointsY?: string;
        alignmentBaseline?: import("csstype").AlignmentBaselineProperty;
        baselineShift?: string | number;
        clipRule?: import("csstype").ClipRuleProperty;
        colorInterpolation?: import("csstype").ColorInterpolationProperty;
        colorRendering?: import("csstype").ColorRenderingProperty;
        dominantBaseline?: import("csstype").DominantBaselineProperty;
        fill?: string;
        fillOpacity?: import("csstype").GlobalsNumber;
        fillRule?: import("csstype").ClipRuleProperty;
        floodColor?: string;
        floodOpacity?: import("csstype").GlobalsNumber;
        glyphOrientationVertical?: string | number;
        lightingColor?: string;
        marker?: string;
        markerEnd?: string;
        markerMid?: string;
        markerStart?: string;
        shapeRendering?: import("csstype").ShapeRenderingProperty;
        stopColor?: string;
        stopOpacity?: import("csstype").GlobalsNumber;
        stroke?: string;
        strokeDasharray?: string | number;
        strokeDashoffset?: string | number;
        strokeLinecap?: import("csstype").StrokeLinecapProperty;
        strokeLinejoin?: import("csstype").StrokeLinejoinProperty;
        strokeMiterlimit?: import("csstype").GlobalsNumber;
        strokeOpacity?: import("csstype").GlobalsNumber;
        strokeWidth?: string | number;
        textAnchor?: import("csstype").TextAnchorProperty;
        vectorEffect?: import("csstype").VectorEffectProperty;
    };
    updateFrameRect(): void;
    move(index: number, direction?: number): void;
    next: () => void;
    prev: () => void;
    initialize(): void;
    handleTouchStart: (e: any) => void;
    handleTouchMove: (e: any) => boolean;
    handleTouchEnd: () => void;
    judgeSwipeDirection(startX: number, startY: number, endX: number, endY: number): 0 | 1 | -1;
}
