/// <reference types="react" />
import * as React from 'react';
export interface Touch {
    startX: number;
    startY: number;
    endX: number;
    endY: number;
    swipeDirection: number;
}
export interface CarouselProps {
    label?: string;
    useDots?: boolean;
    dotStyle?: React.CSSProperties;
    activeDotStyle?: React.CSSProperties;
    duration?: number;
    autoSlideInterval?: number;
    style?: React.CSSProperties;
    useControl?: boolean;
}
export interface CarouselState {
    animate: boolean;
    canUseDOM: boolean;
    currentIndex: number;
    slideCount: number;
    slideWidth: any;
    slideHeight: any;
    swipePosition: number;
    showIndex: number;
}
export default class Carousel extends React.Component<CarouselProps, CarouselState> {
    id: number;
    container: Element;
    swiping: boolean;
    moving: boolean;
    direction: number;
    touch: Touch;
    timer: any;
    state: CarouselState;
    static readonly defaultProps: CarouselProps;
    constructor();
    componentWillMount(): void;
    componentDidMount(): void;
    componentDidUpdate(prevProps: any): void;
    componentWillUnmount(): void;
    render(): JSX.Element;
    renderInitialRect(): JSX.Element;
    renderCarouselChild(): JSX.Element | JSX.Element[];
    renderControls(): JSX.Element;
    renderNextButton(action: any): JSX.Element;
    renderPrevButton(action: any): JSX.Element;
    autoSlide(): void;
    resetAutoSlide(): void;
    addEvents(): void;
    removeEvents(): void;
    onResize(): void;
    getFrameStyle(): any;
    getSlideStyle(index: any): any;
    canDisplaySlide(index: any): boolean;
    getNextIndex(): number;
    getPrevIndex(): number;
    getIndexDirection(index: any): 0 | 1 | -1;
    getButtonStyle(isActive: any): {
        alignContent?: "center" | "initial" | "inherit" | "unset" | "flex-start" | "flex-end" | "space-between" | "space-around" | "stretch";
        alignItems?: "center" | "initial" | "inherit" | "unset" | "flex-start" | "flex-end" | "stretch" | "baseline";
        alignSelf?: "auto" | "center" | "initial" | "inherit" | "unset" | "flex-start" | "flex-end" | "stretch" | "baseline";
        alignmentAdjust?: any;
        alignmentBaseline?: any;
        animationDelay?: any;
        animationDirection?: any;
        animationIterationCount?: any;
        animationName?: any;
        animationPlayState?: any;
        appearance?: any;
        backfaceVisibility?: any;
        'background': any;
        backgroundAttachment?: "scroll" | "initial" | "inherit" | "unset" | "fixed" | "local";
        backgroundBlendMode?: any;
        backgroundColor?: any;
        backgroundComposite?: any;
        backgroundImage?: any;
        backgroundOrigin?: any;
        backgroundPosition?: any;
        backgroundRepeat?: any;
        baselineShift?: any;
        behavior?: any;
        border: any;
        borderBottom?: any;
        borderBottomColor?: any;
        borderBottomLeftRadius?: any;
        borderBottomRightRadius?: any;
        borderBottomStyle?: any;
        borderBottomWidth?: any;
        borderCollapse?: any;
        borderColor?: any;
        borderCornerShape?: any;
        borderImageSource?: any;
        borderImageWidth?: any;
        borderLeft?: any;
        borderLeftColor?: any;
        borderLeftStyle?: any;
        borderLeftWidth?: any;
        borderRight?: any;
        borderRightColor?: any;
        borderRightStyle?: any;
        borderRightWidth?: any;
        borderSpacing?: any;
        borderStyle?: any;
        borderTop?: any;
        borderTopColor?: any;
        borderTopLeftRadius?: any;
        borderTopRightRadius?: any;
        borderTopStyle?: any;
        borderTopWidth?: any;
        borderWidth?: any;
        bottom?: any;
        boxAlign?: any;
        boxDecorationBreak?: any;
        boxDirection?: any;
        boxLineProgression?: any;
        boxLines?: any;
        boxOrdinalGroup?: any;
        boxFlex?: number | "initial" | "inherit" | "unset";
        boxFlexGroup?: number | "initial" | "inherit" | "unset";
        boxShadow?: any;
        breakAfter?: any;
        breakBefore?: any;
        breakInside?: any;
        clear?: any;
        clip?: any;
        clipRule?: any;
        color?: any;
        columnCount?: number | "auto" | "initial" | "inherit" | "unset";
        columnFill?: any;
        columnGap?: any;
        columnRule?: any;
        columnRuleColor?: any;
        columnRuleWidth?: any;
        columnSpan?: any;
        columnWidth?: any;
        columns?: any;
        counterIncrement?: any;
        counterReset?: any;
        cue?: any;
        cueAfter?: any;
        cursor: any;
        direction?: any;
        display?: any;
        fill?: any;
        fillOpacity?: number | "initial" | "inherit" | "unset";
        fillRule?: any;
        filter?: any;
        flex?: string | number;
        flexAlign?: any;
        flexBasis?: any;
        flexDirection?: "initial" | "inherit" | "unset" | "row" | "row-reverse" | "column" | "column-reverse";
        flexFlow?: string;
        flexGrow?: number | "initial" | "inherit" | "unset";
        flexItemAlign?: any;
        flexLinePack?: any;
        flexOrder?: any;
        flexShrink?: number | "initial" | "inherit" | "unset";
        flexWrap?: "initial" | "inherit" | "unset" | "nowrap" | "wrap" | "wrap-reverse";
        float?: any;
        flowFrom?: any;
        font?: any;
        fontFamily?: any;
        fontKerning?: any;
        fontSize?: string | number;
        fontSizeAdjust?: number | "none" | "initial" | "inherit" | "unset";
        fontStretch?: "initial" | "inherit" | "unset" | "normal" | "ultra-condensed" | "extra-condensed" | "condensed" | "semi-condensed" | "semi-expanded" | "expanded" | "extra-expanded" | "ultra-expanded";
        fontStyle?: "initial" | "inherit" | "unset" | "normal" | "italic" | "oblique";
        fontSynthesis?: any;
        fontVariant?: any;
        fontVariantAlternates?: any;
        fontWeight?: "initial" | "inherit" | "unset" | "normal" | "bold" | "bolder" | "lighter" | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;
        gridArea?: any;
        gridColumn?: any;
        gridColumnEnd?: any;
        gridColumnStart?: any;
        gridRow?: any;
        gridRowEnd?: any;
        gridRowPosition?: any;
        gridRowSpan?: any;
        gridTemplateAreas?: any;
        gridTemplateColumns?: any;
        gridTemplateRows?: any;
        height?: any;
        hyphenateLimitChars?: any;
        hyphenateLimitLines?: any;
        hyphenateLimitZone?: any;
        hyphens?: any;
        imeMode?: any;
        justifyContent?: "center" | "initial" | "inherit" | "unset" | "flex-start" | "flex-end" | "space-between" | "space-around" | "space-evenly";
        layoutGrid?: any;
        layoutGridChar?: any;
        layoutGridLine?: any;
        layoutGridMode?: any;
        layoutGridType?: any;
        left?: any;
        letterSpacing?: any;
        lineBreak?: any;
        lineClamp?: number | "initial" | "inherit" | "unset";
        lineHeight: string | number;
        listStyle?: any;
        listStyleImage?: any;
        listStylePosition?: any;
        listStyleType?: any;
        margin: any;
        marginBottom?: any;
        marginLeft?: any;
        marginRight?: any;
        marginTop?: any;
        marqueeDirection?: any;
        marqueeStyle?: any;
        mask?: any;
        maskBorder?: any;
        maskBorderRepeat?: any;
        maskBorderSlice?: any;
        maskBorderSource?: any;
        maskBorderWidth?: any;
        maskClip?: any;
        maskOrigin?: any;
        maxFontSize?: any;
        maxHeight?: any;
        maxWidth?: any;
        minHeight?: any;
        minWidth?: any;
        opacity?: number | "initial" | "inherit" | "unset";
        order?: number | "initial" | "inherit" | "unset";
        orphans?: number | "initial" | "inherit" | "unset";
        outline?: any;
        outlineColor?: any;
        outlineOffset?: any;
        overflow?: "auto" | "hidden" | "visible" | "scroll" | "initial" | "inherit" | "unset";
        overflowStyle?: any;
        overflowX?: "auto" | "hidden" | "visible" | "scroll" | "initial" | "inherit" | "unset";
        overflowY?: "auto" | "hidden" | "visible" | "scroll" | "initial" | "inherit" | "unset";
        padding: any;
        paddingBottom?: any;
        paddingLeft?: any;
        paddingRight?: any;
        paddingTop?: any;
        pageBreakAfter?: any;
        pageBreakBefore?: any;
        pageBreakInside?: any;
        pause?: any;
        pauseAfter?: any;
        pauseBefore?: any;
        perspective?: any;
        perspectiveOrigin?: any;
        pointerEvents?: any;
        position?: "initial" | "inherit" | "unset" | "fixed" | "static" | "relative" | "absolute" | "sticky";
        punctuationTrim?: any;
        quotes?: any;
        regionFragment?: any;
        restAfter?: any;
        restBefore?: any;
        right?: any;
        rubyAlign?: any;
        rubyPosition?: any;
        shapeImageThreshold?: any;
        shapeInside?: any;
        shapeMargin?: any;
        shapeOutside?: any;
        speak?: any;
        speakAs?: any;
        strokeOpacity?: number | "initial" | "inherit" | "unset";
        strokeWidth?: string | number;
        tabSize?: any;
        tableLayout?: any;
        textAlign?: any;
        textAlignLast?: any;
        textDecoration?: any;
        textDecorationColor?: any;
        textDecorationLine?: any;
        textDecorationLineThrough?: any;
        textDecorationNone?: any;
        textDecorationOverline?: any;
        textDecorationSkip?: any;
        textDecorationStyle?: any;
        textDecorationUnderline?: any;
        textEmphasis?: any;
        textEmphasisColor?: any;
        textEmphasisStyle?: any;
        textHeight?: any;
        textIndent?: any;
        textJustifyTrim?: any;
        textKashidaSpace?: any;
        textLineThrough?: any;
        textLineThroughColor?: any;
        textLineThroughMode?: any;
        textLineThroughStyle?: any;
        textLineThroughWidth?: any;
        textOverflow?: any;
        textOverline?: any;
        textOverlineColor?: any;
        textOverlineMode?: any;
        textOverlineStyle?: any;
        textOverlineWidth?: any;
        textRendering?: any;
        textScript?: any;
        textShadow?: any;
        textTransform?: any;
        textUnderlinePosition?: any;
        textUnderlineStyle?: any;
        top?: any;
        touchAction?: any;
        transform?: any;
        transformOrigin?: any;
        transformOriginZ?: any;
        transformStyle?: any;
        transition?: any;
        transitionDelay?: any;
        transitionDuration?: any;
        transitionProperty?: any;
        transitionTimingFunction?: any;
        unicodeBidi?: any;
        unicodeRange?: any;
        userFocus?: any;
        userInput?: any;
        verticalAlign?: any;
        visibility?: any;
        voiceBalance?: any;
        voiceDuration?: any;
        voiceFamily?: any;
        voicePitch?: any;
        voiceRange?: any;
        voiceRate?: any;
        voiceStress?: any;
        voiceVolume?: any;
        whiteSpace?: any;
        whiteSpaceTreatment?: any;
        widows?: number | "initial" | "inherit" | "unset";
        width?: any;
        wordBreak?: any;
        wordSpacing?: any;
        wordWrap?: any;
        wrapFlow?: any;
        wrapMargin?: any;
        wrapOption?: any;
        writingMode?: any;
        zIndex?: number | "auto" | "initial" | "inherit" | "unset";
        zoom?: string | number;
        borderRadius: string;
    };
    updateFrameRect(): void;
    move(index: number, direction?: number): void;
    next(): void;
    prev(): void;
    initialize(): void;
    handleTouchStart(e: any): void;
    handleTouchMove(e: any): boolean;
    handleTouchEnd(): void;
    judgeSwipeDirection(startX: number, startY: number, endX: number, endY: number): 0 | 1 | -1;
}
